config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  resources :sessions, only: %i[ index new create show destroy ]

  resources :events do
    member do
      post :finalize
      post :ready
      post :audit
      post :redraw
    end
    resources :notes, only: %i[ create ], controller: "events/notes"
    resources :products, only: %i[ show ], controller: "events/products"
    resources :reservations, only: %i[ index create destroy ], controller: "events/reservations"
  end

  resources :reservations, only: %i[ update ]

  resources :groups do
    resources :members, only: %i[ create ]
    resources :memberships, only: %i[ create destroy ]
    resources :troops,  only: %i[ create ]
  end

  resources :members, only: %i[ edit update destroy ]

  resources :troops, only: %i[ edit update destroy ]

  resources :reports, only: %i[ index show ]

  resources :consumables do
    resources :notes, only: %i[ create ], controller: "consumables/notes"
    resources :transactions, only: %i[ create destroy ], controller: "consumable_transactions"

    resources :images, only: %i[ update destroy ], controller: "entities/images" do
      member do
        patch :left
        patch :right
      end
    end
  end

  resources :products do
    member do
      post :convert
    end

    resources :notes, only: %i[ create ], controller: "products/notes"
    resources :instances, only: %i[destroy], controller: "products/instances" do
      member do
        patch :hold
        patch :send_for_repairs
        patch :repair
      end
    end

    resources :images, only: %i[ update destroy ], controller: "entities/images" do
      member do
        patch :left
        patch :right
      end
    end
  end

  resources :instances, only: %i[ edit update ]

  resources :notes

  get "/apple-touch-icon/:size.:format", to: "home#apple_touch_icon"
  get "/favicon/:size.:format", to: "home#apple_touch_icon"
end

app/models/group.rb
class Group < ApplicationRecord
  include HasSlug

  has_one_attached :logo

  has_many :troops,        dependent: :delete_all, autosave: true
  has_many :products,      dependent: :delete_all, autosave: true
  has_many :consumables,   dependent: :delete_all, autosave: true
  has_many :events,        dependent: :delete_all, autosave: true
  has_many :members,       dependent: :delete_all, autosave: true
  has_many :domain_events, dependent: :delete_all, autosave: true, as: :model
  has_many :instances,     through: :products
  has_many :reservations,  through: :instances

  validates :name, presence: true, length: { minimum: 2 }

  def has_logo?
    logo.attachment.present?
  end

  def inventory_directors
    members.select(&:inventory_director?)
  end

  def accountants
    members.select(&:accountant?)
  end

  def find_note_by_slug!(slug)
    notes = Note.find_by_sql(find_note_by_slug_sql(slug))

    raise ActiveRecord::RecordNotFound if notes.empty?
    notes.first
  end

  def register_new_troop(attributes, metadata: {})
    troops.build(attributes).tap do |new_troop|
      domain_events << TroopRegistered.new(
        data: {
          name: new_troop.name,
        },
        metadata: metadata
      )
    end
  end

  def register_new_event(attributes, metadata: {})
    events.build(attributes).tap do |new_event|
      domain_events << EventRegistered.new(
        data: {
          description: new_event.description,
          end_on: new_event.end_on,
          event_slug: new_event.slug,
          group_slug: slug,
          start_on: new_event.start_on,
          title: new_event.title,
        },
        metadata: metadata
      )
    end
  end

  def register_new_product(attributes, metadata: {})
    products.build(attributes).tap do |new_product|
      domain_events << ProductRegistered.new(
        data: {
          aisle: new_product.aisle,
          building: new_product.building,
          categories: new_product.categories.map(&:name),
          description: new_product.description,
          group_slug: self.slug,
          name: new_product.name,
          product_slug: new_product.slug,
          shelf: new_product.shelf,
          unit: new_product.unit,
        },
        metadata: metadata
      )
    end
  end

  def register_new_consumable(attributes, metadata: {})
    consumables.build(attributes).tap do |new_consumable|
      domain_events << ConsumableRegistered.new(
        data: {
          aisle: new_consumable.aisle,
          building: new_consumable.building,
          categories: new_consumable.categories.map(&:name),
          description: new_consumable.description,
          group_slug: self.slug,
          name: new_consumable.name,
          consumable_slug: new_consumable.slug,
          shelf: new_consumable.shelf,
          unit: new_consumable.unit,
        },
        metadata: metadata
      )
    end
  end

  def register_new_member(attributes, metadata: {})
    members.build(name: attributes.fetch(:name), email: attributes.fetch(:email)).tap do |new_member|
      domain_events << MemberRegistered.new(
        data: {
          email: new_member.email,
          group_slug: self.slug,
          name: new_member.name,
          user_slug:  new_member.slug,
        },
        metadata: metadata
      )
    end
  end

  def convert_product_to_consumable(product_slug, reason, metadata)
    product = products.detect{|product| product.slug == product_slug}
    raise ActiveRecord::RecordNotFound, "Could not find product with slug #{product_slug.inspect}" unless product

    attributes = {
      group: product.group,
      name: product.name,
      description: product.description,
      slug: product.slug,
      aisle: product.aisle,
      shelf: product.shelf,
      unit: product.unit,
      building: product.building,
      internal_unit_price: product.internal_unit_price,
      external_unit_price: product.external_unit_price,

      base_quantity: QuantityParser.new.parse("1 unit"),
    }

    register_new_consumable(attributes, metadata: metadata).tap do |consumable|
      consumable.categories = product.categories
      product.images.detach.each do |image|
        consumable.images.attach(image.blob)
      end if product.images.detach&.any?

      quantity = QuantityParser.new.parse("#{product.available_quantity} unit")
      consumable.change_quantity(quantity, unit_price: 0, reason: reason)
      product.destroy

      domain_events << ProductConvertedToConsumable.new(
        data: {
          group_slug: self.slug,
          product_slug: slug,
        },
        metadata: metadata
      )
    end
  end

  private

  def find_note_by_slug_sql(slug)
    <<~EOSQL.squish.gsub(":quoted_slug", Note.connection.quote(slug)).gsub(":quoted_group_id", Note.connection.quote(id))
      SELECT notes.*
      FROM notes
      JOIN events ON events.id = notes.parent_id AND notes.parent_type = 'Event'
      WHERE notes.slug = :quoted_slug
        AND events.group_id = :quoted_group_id

      UNION

      SELECT notes.*
      FROM notes
      JOIN products ON products.id = notes.parent_id AND notes.parent_type = 'Product'
      WHERE notes.slug = :quoted_slug
        AND products.group_id = :quoted_group_id
    EOSQL
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @page_title = t(".page_title")

    @groups = Group.all
  end

  def show
    @page_title = @group.name

    @member = @group.members.build
    @troop  = @group.troops.build
  end

  def new
    @page_title = t(".page_title")

    @group = Group.new
  end

  def edit
    @page_title = t(".page_title", group_name: @group.name)
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: t(".group_successfully_created")
    else
      @page_title = t(".page_title")
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: t(".group_successfully_updated")
    else
      @page_title = t(".page_title", group_name: @group.name)
      render :edit
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      redirect_to groups_url, notice: t(".group_successfully_destroyed")
    end
  end

  private

  def set_group
    @group = current_group
  end

  def group_params
    params.require(:group).permit(:name, :logo, :address)
  end
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <div class="grid-container">
    <div class="grid-x grid-padding-x">
      <% if group.errors.any? %>
        <div class="small-12 cell">
          <div id="error_explanation">
            <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

            <ul>
              <% group.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="small-12 cell">
        <%= form.label :name %>
        <%= form.text_field :name, autocomplete: false %>
      </div>

      <div class="small-12 cell">
        <%= form.label :logo %>
        <%= form.file_field :logo %>
      </div>

      <div class="small-12 cell">
        <%= form.label :address %>
        <%= form.text_area :address, size: "80x5" %>
      </div>

      <div class="small-12 cell">
        <%= form.submit class: "button primary" %>
        <%= render partial: "shared/or" %>
        <% if @group.new_record? %>
          <%= link_to t(".cancel_button_label"), groups_path, class: "button secondary" %>
        <% else %>
          <%= link_to t(".cancel_button_label"), @group, class: "button secondary" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<div class="grid-x grid-padding-x">
  <div class="cell large-9 medium-12">
    <%= link_to t(".new_group_button_label") , new_group_path, class: "button hide-for-large" %>

    <table class="hover stack">
      <thead>
        <tr>
          <th><%= t(".name_header") %></th>
        </tr>
      </thead>

      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <td><%= link_to group.name, group %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="cell large-3 medium-12 show-for-large">
    <%= link_to t(".new_group_button_label"), new_group_path, class: "button expanded" %>
  </div>
</div>

app/views/groups/new.html.erb
<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<div class="grid-x grid-margin-x">
  <div class="large-9 medium-12 cell">
    <%= link_to t(".edit_button_label"), edit_group_path(@group), class: "button large hide-for-large" %>
    <%= link_to t(".back_to_list"), groups_path, class: "button secondary large hide-for-large" %>

    <h2>
      <% if @group.logo.attached? %>
        <%= image_tag @group.logo.variant(resize: "x55"), alt: "", height: 55, style: "max-height: 55px" %>
      <% end %>
      <%= t(".members") %>
    </h2>
    <% @group.troops.reject(&:new_record?).sort_by(&:sort_key).each do |troop| %>
      <table class="hover stack">
        <caption><%= link_to troop.name, edit_troop_path(troop) %></caption>
        <thead>
          <tr>
            <th><%= t(".name_header") %></th>
            <th><%= t(".email_header") %></th>
          </tr>
        </thead>
        <tbody>
          <% troop.members.reject(&:new_record?).sort_by(&:sort_key).each do |member| %>
            <tr>
              <td><%= link_to member.name, edit_member_path(member) %></td>
              <td>
                <%= form_for :membership, url: group_membership_path(@group, member.memberships.detect{|m| m.troop == troop}), method: :delete do |form| %>
                  <%= mail_to member.email %>
                  <%= form.submit t(".unattach"), class: "button alert small" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="2">
              <%= form_for :membership, url: group_memberships_path(@group) do |form| %>
                <%= form.hidden_field :troop_slug, value: troop.slug %>
                <%= form.label :email, t(".attach_member", troop_name: troop.name) %>
                <%= form.text_field :email, autocomplete: false, placeholder: t(".attach_member_email_placeholder") %>
                <%= form.submit t(".attach_button_label"), class: "button secondary" %>
              <% end %>
            </td>
          </tr>
        </tfoot>
      </table>
    <% end %>
    <% if (@group.members.reject(&:new_record?) - @group.troops.map(&:members).flatten).any? %>
      <table class="hover stack">
        <caption><%= t(".unattached") %></caption>
        <thead>
          <tr>
            <th><%= t(".name_header") %></th>
            <th><%= t(".email_header") %></th>
          </tr>
        </thead>
        <tbody>
          <% (@group.members.reject(&:new_record?) - @group.troops.map(&:members).flatten).sort_by(&:sort_key).each do |member| %>
            <tr>
              <td><%= link_to member.name, edit_member_path(member) %></td>
              <td><%= mail_to member.email %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <div class="large-3 medium-12 cell show-for-large">
    <%= link_to t(".edit_button_label"), edit_group_path(@group), class: "button expanded" %>
    <%= link_to t(".back_to_list_button_label"), groups_path, class: "button secondary expanded" %>

    <hr>

    <h3><%= t(".add_troop_header") %></h3>
    <%= form_for @troop, url: group_troops_path(@group) do |form| %>
      <%= form.label :name %>
      <%= form.text_field :name, autocomplete: false %>

      <%= form.label :position %>
      <%= form.number_field :position, autocomplete: false %>

      <%= form.submit class: "button primary" %>
    <% end %>

    <hr>

    <h3><%= t(".add_member_header") %></h3>
    <%= form_for @member, url: group_members_path(@group) do |form| %>
      <%= form.label :name %>
      <%= form.text_field :name, autocomplete: false %>

      <%= form.label :email %>
      <%= form.email_field :email, autocomplete: false %>

      <%= form.submit class: "button primary" %>
    <% end %>
  </div>
</div>