config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  resources :sessions, only: %i[ index new create show destroy ]

  resources :events do
    member do
      post :finalize
      post :ready
      post :audit
      post :redraw
    end
    resources :notes, only: %i[ create ], controller: "events/notes"
    resources :products, only: %i[ show ], controller: "events/products"
    resources :reservations, only: %i[ index create destroy ], controller: "events/reservations"
  end

  resources :reservations, only: %i[ update ]

  resources :groups do
    resources :members, only: %i[ create ]
    resources :memberships, only: %i[ create destroy ]
    resources :troops,  only: %i[ create ]
  end

  resources :members, only: %i[ edit update destroy ]

  resources :troops, only: %i[ edit update destroy ]

  resources :reports, only: %i[ index show ]

  resources :consumables do
    resources :notes, only: %i[ create ], controller: "consumables/notes"
    resources :transactions, only: %i[ create destroy ], controller: "consumable_transactions"

    resources :images, only: %i[ update destroy ], controller: "entities/images" do
      member do
        patch :left
        patch :right
      end
    end
  end

  resources :products do
    member do
      post :convert
    end

    resources :notes, only: %i[ create ], controller: "products/notes"
    resources :instances, only: %i[destroy], controller: "products/instances" do
      member do
        patch :hold
        patch :send_for_repairs
        patch :repair
      end
    end

    resources :images, only: %i[ update destroy ], controller: "entities/images" do
      member do
        patch :left
        patch :right
      end
    end
  end

  resources :instances, only: %i[ edit update ]

  resources :notes

  get "/apple-touch-icon/:size.:format", to: "home#apple_touch_icon"
  get "/favicon/:size.:format", to: "home#apple_touch_icon"
end

app/views/shared/_alert.html.erb
<div class="callout alert" data-closeable>
  <p><%= alert %></p>
</div>

app/views/shared/_image.html.erb
<div class="cell entity-image" id="entity-<%= entity.slug %>-image-<%= image.id %>">
  <div class="card">
    <%= link_to image_tag(image.variant(WEB_IMAGE_CONFIG.merge(resize: "300x225")), alt: "", size: "300x225"), image, class: "thumbnail" %>
    <% if current_member.inventory_director?  %>
      <div class="card-section">
        <div class="grid-x grid-margin-x">
          <div class="auto cell">
            <%= button_to t(".rotate_image_left_button_label_html"), left_product_image_path(entity, image), remote: true, method: :patch, class: "button small primary" if entity.kind_of?(Product) %>
            <%= button_to t(".rotate_image_left_button_label_html"), left_consumable_image_path(entity, image), remote: true, method: :patch, class: "button small primary" if entity.kind_of?(Consumable) %>
          </div>
          <div class="auto cell">
            <%= button_to t(".rotate_image_right_button_label_html"), right_product_image_path(entity, image), remote: true, method: :patch, class: "button small primary" if entity.kind_of?(Product) %>
            <%= button_to t(".rotate_image_right_button_label_html"), right_consumable_image_path(entity, image), remote: true, method: :patch, class: "button small primary" if entity.kind_of?(Consumable) %>
          </div>
          <div class="auto cell">
            <%= button_to t(".delete_image_button_label"), product_image_path(entity, image), remote: true, method: :delete, class: "button small alert" if entity.kind_of?(Product) %>
            <%= button_to t(".delete_image_button_label"), consumable_image_path(entity, image), remote: true, method: :delete, class: "button small alert" if entity.kind_of?(Consumable) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_notes.html.erb
<h3><%= t(".notes_header") %></h3>

<%= form_for note, url: create_note_path do |form| %>
  <%= form.label :body, t(".add_note_label") %>
  <%= form.text_area :body, size: "10x3" %>
  <%= form.submit t(".create_note_button_label"), class: "button primary small" %>
<% end %>

<% if parent.notes.reject(&:new_record?).any? %>
  <% parent.notes.reject(&:new_record?).sort_by(&:created_at).reverse.each do |note| %>
    <div id="note-<%= note.slug %>">
      <hr>
      <% if note.author == current_member %>
        <%= button_to t(".delete_note_button_label"), note, method: :delete, remote: true, class: "button tiny alert float-right" %>
      <% end %>
      <%= simple_format note.body %>
      <p><small><%= t(".by_author_name", author_name: note.author_name) %>, <span title="<%= note.created_at.to_formatted_s(:iso8601) %>"><%= t("date.formats.time_ago", date: time_ago_in_words(note.created_at)) %></span></small></p>
    </div>
  <% end %>
<% end %>

app/views/shared/_notice.html.erb
<div class="callout success" data-closeable>
  <p><%= notice %></p>
</div>

app/views/shared/_notices.html.erb
<% if notice.present? %>
  <%= render partial: "shared/notice", locals: {notice: notice} %>
<% end %>
<% if alert.present? %>
  <%= render partial: "shared/alert", locals: {alert: alert} %>
<% end %>

app/views/shared/_or.html.erb
<span class="clear button secondary"><%= t(".or") %></span>