config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  resources :sessions, only: %i[ index new create show destroy ]

  resources :events do
    member do
      post :finalize
      post :ready
      post :audit
      post :redraw
    end
    resources :notes, only: %i[ create ], controller: "events/notes"
    resources :products, only: %i[ show ], controller: "events/products"
    resources :reservations, only: %i[ index create destroy ], controller: "events/reservations"
  end

  resources :reservations, only: %i[ update ]

  resources :groups do
    resources :members, only: %i[ create ]
    resources :memberships, only: %i[ create destroy ]
    resources :troops,  only: %i[ create ]
  end

  resources :members, only: %i[ edit update destroy ]

  resources :troops, only: %i[ edit update destroy ]

  resources :reports, only: %i[ index show ]

  resources :consumables do
    resources :notes, only: %i[ create ], controller: "consumables/notes"
    resources :transactions, only: %i[ create destroy ], controller: "consumable_transactions"

    resources :images, only: %i[ update destroy ], controller: "entities/images" do
      member do
        patch :left
        patch :right
      end
    end
  end

  resources :products do
    member do
      post :convert
    end

    resources :notes, only: %i[ create ], controller: "products/notes"
    resources :instances, only: %i[destroy], controller: "products/instances" do
      member do
        patch :hold
        patch :send_for_repairs
        patch :repair
      end
    end

    resources :images, only: %i[ update destroy ], controller: "entities/images" do
      member do
        patch :left
        patch :right
      end
    end
  end

  resources :instances, only: %i[ edit update ]

  resources :notes

  get "/apple-touch-icon/:size.:format", to: "home#apple_touch_icon"
  get "/favicon/:size.:format", to: "home#apple_touch_icon"
end

app/models/product.rb
require "net/http"
require "stringio"

class Product < ApplicationRecord
  include HasSlug

  has_many_attached :images

  belongs_to :group
  has_many :product_categories, dependent: :delete_all, autosave: true
  has_many :notes,              dependent: :delete_all, autosave: true, as: :parent
  has_many :domain_events,      dependent: :delete_all, autosave: true, as: :model
  has_many :categories,         dependent: :delete_all, autosave: true,              through: :product_categories
  has_many :instances,          dependent: :delete_all, autosave: true
  has_many :reservations,                               autosave: true,              through: :instances

  scope :by_name,               ->{ order(Arel.sql("UNACCENT(#{quoted_table_name}.name), #{quoted_table_name}.id")) }
  scope :with_reservations,     ->{ includes(reservations: :event) }
  scope :with_categories,       ->{ includes(:categories) }
  scope :with_instances,        ->{ includes(:instances) }
  scope :not_recently_reserved, ->{ joins("LEFT JOIN instances ON instances.product_id = products.id LEFT JOIN reservations ON reservations.instance_id = instances.id").where("reservations.created_at IS NULL OR reservations.created_at < ?", 12.months.ago).order(Arel.sql("random()")) }
  scope :leased,                ->{ includes(:reservations).references(:reservations).where(reservations: {returned_on: nil}).where.not(reservations: {leased_on: nil}) }
  scope :available,             ->{ includes(:reservations, :instances).references(:reservations, :instances).where(instances: {state: "available"}, reservations: {id: nil}) }
  scope :in_category,           ->(category){ includes(:categories).where(categories: { slug: category.slug }) }
  scope :reserved,              ->(on_event=nil){
    if on_event
      includes(:reservations).references(:reservations).where(reservations: {event_id: on_event.id})
    else
      includes(:reservations).references(:reservations).where.not(reservations: {event_id: nil})
    end
  }
  scope :double_booked,         ->(event) {
    select(<<~EOSQL)
              products.*
            , events.id       AS double_booked_event_id
            , events.slug     AS double_booked_event_slug
            , events.title    AS double_booked_event_title
            , events.start_on AS double_booked_event_start_on
            , events.end_on   AS double_booked_event_end_on
            , array_agg(instances.id) AS double_booked_instance_ids
            EOSQL
              .joins("JOIN instances    ON instances.product_id     = products.id".squish)
              .joins("JOIN reservations ON reservations.instance_id = instances.id".squish)
              .joins("JOIN events       ON events.id                = reservations.event_id".squish)
              .where.not(reservations: { event_id: event.id })
              .where("reservations.instance_id IN (SELECT instance_id FROM reservations WHERE event_id = ?)", event.id)
              .where("daterange(events.start_on - 1, events.end_on + 1, '[]') && daterange(date :start_on - 1, date :end_on + 1, '[]')", start_on: event.start_on, end_on: event.end_on)
              .group("products.id", "events.id")
  }
  scope :search, ->(string){
    vector = "to_tsvector('fr', coalesce(products.name, '') || ' ' || coalesce(products.description, '') || ' ' || coalesce(products.building, ' ') || ' ' || coalesce(products.aisle, ' ') || ' ' || coalesce(products.shelf, ' ') || ' ' || coalesce(products.unit, ' '))"
    query = "plainto_tsquery('fr', :string)"
    where("#{vector} @@ #{query}", string: string).order(Arel.sql("ts_rank(#{vector}, #{query.sub(":string", Product.connection.quote(string))})"))
  }

  validates :name, presence: true, length: { minimum: 2 }
  validates :quantity, numericality: { only_integer: true, greater_than: 0, less_than_or_equal: ->(product){ product.categories.map(&:max_quantity).min || 99 } }
  validates :internal_unit_price, :external_unit_price, numericality: { greater_than_or_equal_to: 0, allow_blank: false }

  before_save :manage_instances
  after_touch :update_instances_count

  # Only used to use the ActionView helpers
  # In reality, this attribute is absolutely unused
  attribute :image_url, :string

  def quantity_on(event)
    event.reservations
      .select{|reservation| reservation.product == self}
      .size
  end

  def unit_price_on(event)
    event.reservations
      .select{|reservation| reservation.product == self}
      .map(&:unit_price)
      .max || unit_price(internal: event.internal?)
  end

  def unit_price(internal: false)
    internal ? internal_unit_price : external_unit_price
  end

  def has_location?
    building.present? || aisle.present? || shelf.present? || unit.present?
  end

  def location_changed?
    building_changed? || aisle_changed? || shelf_changed? || unit_changed?
  end

  def available_quantity
    instances.select(&:available?).size
  end

  def reserved_quantity_on(date_range)
    instances.select do |instance|
      instance.reserved_on?(date_range)
    end.size
  end

  def add_note(attributes, metadata: {})
    notes.build(attributes).tap do |new_note|
      domain_events << NoteAddedToProduct.new(
        data: {
          author_slug: new_note.author_slug,
          body: new_note.body,
          product_slug: slug,
        },
        metadata: metadata
      )
    end
  end

  def change_data(attributes, metadata: {})
    self.attributes = attributes
    domain_events << ProductNameChanged.new(data: {product_slug: slug, name: name, description: description}, metadata: metadata)                           if name_changed? || description_changed?
    domain_events << ProductLocationChanged.new(data: {product_slug: slug, building: building, aisle: aisle, shelf: shelf, unit: unit}, metadata: metadata) if location_changed?
    # domain_events << ProductCategoriesChanged.new(data: {product_slug: slug, categories: categories.map(&:name)}, metadata: metadata)
  end

  def category_slugs
    categories.map(&:slug)
  end

  def category_slugs=(value)
    self.categories = Category.where(slug: Array(value).reject(&:blank?))
  end

  # Returns a string to be used for ordering a list of products consistently
  #
  # @return [String] The key to use to order this item consistently
  def sort_key_for_display
    [name.downcase, id].map(&:to_s).join(":")
  end

  def sort_key_for_pickup
    [building, aisle, shelf, unit, name, id].map(&:to_s).join(":")
  end

  private

  def manage_instances
    if new_record?
      manage_instances_on_create
    else
      manage_instances_on_update
    end
  end

  def manage_instances_on_create
    quantity.times.each do |n|
      instances.build
    end
  end

  def manage_instances_on_update
    return unless quantity_changed?

    if quantity_was > quantity
      manage_instance_removal
    else
      manage_instance_additions
    end
  end

  def quantity_delta
    (quantity - quantity_was).abs
  end

  def manage_instance_removal
    candidates = instances.select(&:has_no_reservations?)
    candidates.first(quantity_delta).each(&:destroy)
    return if quantity_delta <= candidates.size

    # We have to remove instances that have had reservations
    # This is unfortunate, but we accept it
    instances.reject(&:destroyed?).first(quantity_delta - candidates.size).each(&:destroy)
  end

  def manage_instance_additions
    quantity_delta.times{|n| instances.build }
  end

  def update_instances_count
    update_attribute(:quantity, instances.reload.size)
  end
end

app/controllers/events/products_controller.rb
class Events::ProductsController < ::ProductsController
  before_action :set_event

  private

  def set_event
    @event = current_group.events.find_by!(slug: params[:event_id])
  end
end

app/controllers/products/instances_controller.rb
class Products::InstancesController < ApplicationController
  before_action :set_product
  before_action :set_instance

  def hold
    @instance.hold!(metadata: domain_event_metadata)
    respond_to do |format|
      format.html { redirect_to @product, notice: t("products.instances.sent_for_repairs_notice", serial_no: @instance.serial_no) }
      format.js { render action: :refresh_instance_row }
    end
  end

  def send_for_repairs
    @instance.send_for_repairs!(metadata: domain_event_metadata)
    respond_to do |format|
      format.html { redirect_to @product, notice: t("products.instances.sent_for_repairs_notice", serial_no: @instance.serial_no) }
      format.js { render action: :refresh_instance_row }
    end
  end

  def repair
    @instance.repair!(metadata: domain_event_metadata)
    respond_to do |format|
      format.html { redirect_to @product, notice: t("products.instances.repaired_notice", serial_no: @instance.serial_no) }
      format.js { render action: :refresh_instance_row }
    end
  end

  def destroy
    @instance.trash!(metadata: domain_event_metadata)
    respond_to do |format|
      format.html { redirect_to @product, notice: t("products.instances.trashed_notice", serial_no: @instance.serial_no) }
      format.js { render action: :refresh_instance_row }
    end
  end

  private

  def set_product
    @product = current_group.products.find_by!(slug: params[:product_id])
  end

  def set_instance
    @instance = @product.instances.find_by!(slug: params[:id])
  end
end

app/controllers/products/notes_controller.rb
class Products::NotesController < ApplicationController
  def create
    current_group.transaction do
      @product = current_group.products.find_by!(slug: params[:product_id])
      @product.add_note(note_params.merge(author: current_member), metadata: domain_event_metadata)
      @product.save!
    end

    redirect_to product_path(@product)
  end

  private

  def note_params
    params.require(:note).permit(:body)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :convert]
  before_action :load_categories, except: %i[ destroy ]

  def index
    @page_title = t(".page_title")

    @filter = params[:filter]

    @selected_category = @categories.detect{|category| category.slug == params[:category]}

    @products = current_group.products.with_attached_images.with_categories.with_instances
    @products = @products.search(@filter) if @filter.present?
    @products = @products.in_category(@selected_category) if @selected_category
    @products = @products.by_name
    @products = @products.page(params[:page])
  end

  def show
    @page_title = @product.name
    @note = @product.notes.build
  end

  def new
    @page_title = t(".page_title")
    @product =
      if params[:clone_from].present?
        @clone_from = current_group.products.find_by!(slug: params[:clone_from])
        current_group.products.build(
          aisle: @clone_from.aisle,
          building: @clone_from.building,
          categories: @clone_from.categories,
          description: @clone_from.description,
          quantity: @clone_from.quantity,
          images: @clone_from.images,
          name: @clone_from.name,
          shelf: @clone_from.shelf,
          unit: @clone_from.unit,
        )
      else
        current_group.products.build
      end
  end

  def edit
    @page_title = t(".page_title", product_name: @product.name)
  end

  def create
    successful = current_group.transaction do
      @product = current_group.register_new_product(product_params, metadata: domain_event_metadata)

      @attached = []
      @attached.concat(@product.images.attach(params[:product][:images])) if params[:product][:images].present?
      @attached.concat(import(params[:product][:image_url]))

      if params[:clone_from].present?
        @clone_from = current_group.products.find_by!(slug: params[:clone_from])
        @clone_from.images.each do |attachment|
          @product.images.build(blob: attachment.blob)
        end
      end

      current_group.save.tap do
        @attached.each do |image|
          ShrinkImageJob.enqueue(@product.id, image.id)
        end if @attached
      end
    end

    if successful
      redirect_to @product, notice: t(".product_successfully_created")
    else
      @page_title = "New Product"
      render :new
    end
  end

  def update
    successful = current_group.transaction do
      @product.change_data(product_params, metadata: domain_event_metadata)

      @attached = []
      @attached.concat(@product.images.attach(params[:product][:images])) if params[:product][:images].present?
      @attached.concat(import(params[:product][:image_url]))

      @product.save.tap do
        @attached.each do |image|
          ShrinkImageJob.enqueue(@product.id, image.id)
        end if @attached
      end
    end

    if successful
      redirect_to @product, notice: t(".product_successfully_updated")
    else
      @page_title = "Edit #{@product.name}"
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_url, notice: t(".product_successfully_destroyed")
  end

  def convert
    group = @product.group
    consumable = nil
    Group.transaction do
      consumable = group.convert_product_to_consumable(@product.slug, t(".conversion_reason"), metadata: domain_event_metadata)
      group.save!
      consumable.images.each do |image|
        ShrinkImageJob.enqueue(consumable.id, image.id)
      end
    end

    redirect_to consumable, notice: t(".product_successfully_converted")
  end

  private

  def set_product
    @product = current_group.products.with_reservations.find_by!(slug: params[:id])
  end

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :building,
      :aisle,
      :shelf,
      :unit,
      :quantity,
      :internal_unit_price,
      :external_unit_price,
      category_slugs: [],
    )
  end

  def load_categories
    @categories = Category.by_name.to_a
  end

  def import(image_url)
    return [] if image_url.blank?

    uri = URI.parse(image_url)

    response = Net::HTTP.get_response(uri)

    @product.images.attach(
      io: StringIO.new(response.body),
      filename: File.basename(uri.path),
      content_type: response["Content-Type"],
    )
  end
end

app/helpers/product_helper.rb
module ProductHelper
  def format_serial_no(serial_no)
    I18n.t("serial_number", no: serial_no)
  end

  def format_product_location(product, plain: false)
    plain_text = [ product.building, product.aisle, product.shelf, product.unit ].reject(&:blank?).to_sentence(words_connector: " / ", two_words_connector: " / ", last_word_connector: " / ")
    plain ? plain_text : content_tag(:span, plain_text, class: "product-location")
  end
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <%= hidden_field_tag :clone_from, @clone_from&.to_param %>
  <div class="grid-container">
    <div class="grid-x grid-padding-x">
      <% if product.errors.any? %>
        <div class="small-12 cell">
          <div id="error_explanation">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

            <ul>
              <% product.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="small-12 cell">
        <%= form.label :name %>
        <%= form.text_field :name, autocomplete: false %>
      </div>

      <div class="small-12 medium-6 cell">
        <%= form.label :images %>
        <%= form.file_field :images, :multiple => true, :"aria-describedby" => "help-on-images", :autocomplete => false %>
        <p id="help-on-images" class="help-text"><%= t(".help_on_images") %></p>
      </div>

      <div class="small-12 medium-6 cell">
        <%= form.label :image_url %>
        <%= form.text_field :image_url, :"aria-describedby" => "help-on-images" %>
      </div>

      <div class="small-12 cell">
        <fieldset class="fieldset">
          <legend><%= t(".location_label") %></legend>
          <%= form.label :building %>
          <%= form.text_field :building %>

          <%= form.label :aisle %>
          <%= form.text_field :aisle %>

          <%= form.label :shelf %>
          <%= form.text_field :shelf %>

          <%= form.label :unit %>
          <%= form.text_field :unit %>
        </fieldset>
      </div>

      <div class="small-12 cell">
        <%= form.label :description %>
        <%= form.text_area :description, size: "10x5" %>
      </div>

      <div class="small-12 cell">
        <div class="grid-x grid-margin-x">
          <div class="small-12 medium-2 cell">
            <%= form.label :quantity %>
            <%= form.number_field :quantity, min: 0, step: 1 %>
          </div>

          <div class="small-12 medium-3 cell">
            <div class="grid-x grid-margin-x">
              <div class="small-auto cell">
                <%= form.label :internal_unit_price %>
                <%= form.number_field :internal_unit_price, min: 0, step: BigDecimal("0.01") %>
              </div>

              <div class="small-auto cell">
                <%= form.label :external_unit_price %>
                <%= form.number_field :external_unit_price, min: 0, step: BigDecimal("0.01") %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="small-12 cell">
        <fieldset class="fieldset">
          <legend><%= t(".categories_label") %></legend>
          <div class="grid-container">
            <div class="grid-x grid-margin-x small-up-3 medium-up-4">
              <%= form.collection_check_boxes :category_slugs, @categories, :slug, ->(category){ t(category.name, scope: "categories") } do |b| %>
                <div class="cell">
                  <%= b.check_box %> <%= b.label %>
                </div>
              <% end %>
            </div>
          </div>
        </fieldset>
      </div>

      <div class="small-12 cell">
        <%= form.submit class: "button primary" %>
        <%= render partial: "shared/or" %>
        <% if @product.new_record? %>
          <%= link_to t(".cancel_button_label"), products_path, class: "button secondary" %>
        <% else %>
          <%= link_to t(".cancel_button_label"), @product, class: "button secondary" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/products/_instance.html.erb
<tr id="product-<%= @product.slug %>-instance-<%= instance.slug %>" class="instance-<%= instance.state %>">
  <td>
    <% if current_member.inventory_director? %>
      <%= link_to format_serial_no(instance.serial_no), [:edit, instance] %>
    <% else %>
      <%= format_serial_no(instance.serial_no) %>
    <% end %>
  </td>
  <td><%= t(instance.state, scope: "products.instance.states") %></td>
  <td>
    <% if current_member.inventory_director? %>
      <div class="grid-x grid-margin-x">
        <% if instance.state_events.include?(:hold) %>
          <div class="auto cell">
            <%= button_to t(".hold_button_label"), hold_product_instance_path(@product, instance), title: t(".hold_hover_help"), remote: true, method: :patch, class: "button warning small expanded" %>
          </div>
        <% end %>
        <% if instance.state_events.include?(:send_for_repairs) %>
          <div class="auto cell">
            <%= button_to t(".send_for_repair_button_label"), send_for_repairs_product_instance_path(@product, instance), title: t(".send_for_repair_hover_help"), remote: true, method: :patch, class: "button warning small expanded" %>
          </div>
        <% end %>
        <% if instance.state_events.include?(:repair) %>
          <div class="auto cell">
            <%= button_to t(".repair_button_label"), repair_product_instance_path(@product, instance), title: t(".repair_hover_help"), remote: true, method: :patch, class: "button success small expanded" %>
          </div>
        <% end %>
        <% if instance.state_events.include?(:trash) %>
          <div class="auto cell">
            <%= button_to t(".trash_button_label"), product_instance_path(@product, instance), title: t(".trash_hover_help"), remote: true, method: :delete, class: "button alert small expanded" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </td>
</tr>

app/views/products/edit.html.erb
<%= render "form", product: @product %>

app/views/products/index.html.erb
<div class="grid-x grid-padding-x">
  <div class="large-9 medium-12 cell">
    <%= form_tag products_path, method: :get, class: "search-form" do %>
      <div class="grid-container">
        <div class="grid-x grid-padding-x">
          <div class="medium-shrink cell show-for-sr">
            <%= label_tag :filter, t(".filter_label"), class: "middle" %>
          </div>
          <div class="medium-shrink cell">
            <%= text_field_tag :filter, @filter, placeholder: t(".filter_label"), autocomplete: false %>
          </div>

          <div class="medium-shrink cell show-for-sr">
            <%= label_tag :category, t(".category_label"), class: "middle" %>
          </div>
          <div class="medium-shrink cell">
            <%= select_tag :category, options_from_collection_for_select(@categories, :slug, ->(category){ t(category.name, scope: "categories") }, @selected_category ? @selected_category.slug : nil), include_blank: true %>
          </div>

          <div class="medium-auto cell">
            <%= submit_tag t(".search_button_label"), name: nil, class: "button" %> <%= link_to t(".view_all_button_label"), products_path, class: "button secondary" %>
          </div>
        </div>
      </div>
    <% end %>

    <% if current_member.inventory_director? %>
      <div class="grid-container">
        <div class="grid-x grid-margin-x">
          <div class="cell">
            <%= link_to t(".new_product_button_label"), new_product_path, class: "button hide-for-large" %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="grid-container">
      <div class="grid-x grid-margin-x">
        <div class="cell">
          <table class="hover stack product-list">
            <thead>
              <tr>
                <th><%= t(".name_header") %></th>
                <th><%= t(".quantity_header") %></th>
                <th><%= t(".location_header") %></th>
                <th><%= t(".description_header") %></th>
                <th><%= t(".categories_header") %></th>
              </tr>
            </thead>

            <tbody>
              <% if @products.empty? %>
                <tr>
                  <td colspan="5"><%= t(".sorry_no_elements") %></td>
                </tr>
              <% end %>
              <% @products.each do |product| %>
                <tr>
                  <td>
                    <%= link_to product.name, product %> <br>
                    <%= entity_image product, height: 250 %>
                  </td>
                  <td><%= number_with_delimiter product.instances.size %></td>
                  <td><%= format_product_location(product) %></td>
                  <td><%= product.description %></td>
                  <td><%= product.categories.map(&:name).map{|name| t(name, scope: "categories") }.sort_by(&:downcase).to_sentence %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @products %>
        </div>
      </div>
    </div>
  </div>

  <% if current_member.inventory_director %>
    <div class="large-3 medium-12 cell show-for-large">
      <%= link_to t(".new_product_button_label"), new_product_path, class: "button expanded" %>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<%= render "form", product: @product %>

app/views/products/show.html.erb
<div class="grid-x grid-margin-x">
  <div class="large-9 medium-12 cell">
    <%= form_tag event_reservations_path(@event, @product) do %>
      <%= submit_tag t(".add_to_cart_label"), name: :add, class: "button small hide-for-large" %>
    <% end if @event %>
    <%= link_to t(".edit_button_label"), edit_product_path(@product), class: "button small hide-for-large" if current_member.inventory_director? %>
    <%= link_to t(".clone_button_label"), new_product_path(clone_from: @product), class: "button small hide-for-large" if current_member.inventory_director? %>
    <%= link_to t(".back_to_list_button_label"), products_path, class: "button secondary small hide-for-large" %>
    <%= link_to t(".convert_to_consumable_label"), convert_product_path(@product), method: :post, class: "button small warning hide-for-large" if current_member.inventory_director? %>
    <%= link_to t(".delete_button_label"), product_path(@product), method: :delete, class: "button small alert hide-for-large" if current_member.inventory_director? %>

    <div class="grid-x grid-padding-x small-up-1 medium-up-3">
      <% @product.images.select(&:blob).sort_by{|blob| blob.filename.to_s.downcase}.each do |image| %>
        <%= render partial: "shared/image", locals: { entity: @product, image: image } %>
      <% end %>
    </div>

    <div>
      <strong><%= t("name", scope: "activerecord.attributes.product") %>:</strong>
      <%= @product.name %>
    </div>

    <div>
      <strong><%= t("location", scope: "activerecord.attributes.product") %>:</strong>
      <%= format_product_location(@product) %>
    </div>

    <div>
      <strong><%= t("quantity", scope: "activerecord.attributes.product") %>:</strong>
      <%= number_with_delimiter @product.quantity %> / <%= number_with_delimiter @product.available_quantity %>
    </div>

    <div>
      <strong><%= t("internal_unit_price", scope: "activerecord.attributes.product") %>:</strong>
      <%= number_to_currency @product.internal_unit_price %>
    </div>

    <div>
      <strong><%= t("external_unit_price", scope: "activerecord.attributes.product") %>:</strong>
      <%= number_to_currency @product.external_unit_price %>
    </div>

    <div>
      <strong><%= t("description", scope: "activerecord.attributes.product") %>:</strong>
      <%= simple_format @product.description %>
    </div>

    <h3><%= t(".instance_serial_nos_header") %></h3>
    <table class="instances">
      <thead>
        <tr>
          <th><%= t(".serial_no_header") %></th>
          <th><%= t(".state_header") %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @product.instances.sort_by{|instance| [instance.state, instance.serial_no]}.each do |instance| %>
          <%= render partial: "instance", locals: {instance: instance} %>
        <% end %>
      </tbody>
    </table>

    <h3><%= t(".product_reservation_history_header") %></h3>
    <table class="hover">
      <thead>
        <th><%= t(".serial_no_header") %></th>
        <th><%= t(".dates_header") %></th>
        <th><%= t(".event_header") %></th>
      </thead>
      <tbody>
        <% @product.reservations.sort_by{|reservation| [reservation.serial_no, reservation.start_on]}.reverse.each do |reservation| %>
          <tr>
            <td><%= format_serial_no(reservation.serial_no) %></td>
            <td><%= format_date_range(reservation.real_date_range) %></td>
            <td><%= link_to reservation.title, event_reservations_path(reservation.event) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="large-3 medium-12 cell show-for-large">
    <%= form_tag event_reservations_path(@event, @product) do %>
      <h4><%= @event.title %></h4>
      <h6><%= format_date_range(@event.real_date_range) %></h6>
      <%= hidden_field_tag "products[#{@product.slug}]", "1" %>
      <%= submit_tag t(".add_to_cart_label"), name: :add, class: "button expanded" %>
      <hr>
    <% end if @event %>
    <%= link_to t(".edit_button_label"), edit_product_path(@product), class: "button expanded" if current_member.inventory_director? %>
    <%= link_to t(".clone_button_label"), new_product_path(clone_from: @product), class: "button expanded" if current_member.inventory_director? %>
    <%= link_to t(".back_to_list_button_label"), products_path, class: "button secondary expanded" %>

    <hr>

    <% if current_member.inventory_director? %>
      <%= link_to t(".convert_to_consumable_label"), convert_product_path(@product), method: :post, class: "button warning expanded" %>
      <hr>
      <%= link_to t(".delete_button_label"), product_path(@product), method: :delete, class: "button alert expanded" %>
      <hr>
    <% end %>

    <%= render partial: "shared/notes", locals: { parent: @product, note: @note, create_note_path: product_notes_path(@product) } %>
  </div>

  <div class="small-12 cell hide-for-large">
    <hr>
    <%= render partial: "shared/notes", locals: { parent: @product, note: @note, create_note_path: product_notes_path(@product) } %>
  </div>

  <div class="small-12 cell hide-for-large">
    <%= link_to t(".back_to_list_button_label"), products_path, class: "button secondary small hide-for-large" %>
  </div>
</div>