config/routes.rb
Rails.application.routes.draw do
  root to: "home#show"

  resources :sessions, only: %i[ index new create show destroy ]

  resources :events do
    member do
      post :finalize
      post :ready
      post :audit
      post :redraw
    end
    resources :notes, only: %i[ create ], controller: "events/notes"
    resources :products, only: %i[ show ], controller: "events/products"
    resources :reservations, only: %i[ index create destroy ], controller: "events/reservations"
  end

  resources :reservations, only: %i[ update ]

  resources :groups do
    resources :members, only: %i[ create ]
    resources :memberships, only: %i[ create destroy ]
    resources :troops,  only: %i[ create ]
  end

  resources :members, only: %i[ edit update destroy ]

  resources :troops, only: %i[ edit update destroy ]

  resources :reports, only: %i[ index show ]

  resources :consumables do
    resources :notes, only: %i[ create ], controller: "consumables/notes"
    resources :transactions, only: %i[ create destroy ], controller: "consumable_transactions"

    resources :images, only: %i[ update destroy ], controller: "entities/images" do
      member do
        patch :left
        patch :right
      end
    end
  end

  resources :products do
    member do
      post :convert
    end

    resources :notes, only: %i[ create ], controller: "products/notes"
    resources :instances, only: %i[destroy], controller: "products/instances" do
      member do
        patch :hold
        patch :send_for_repairs
        patch :repair
      end
    end

    resources :images, only: %i[ update destroy ], controller: "entities/images" do
      member do
        patch :left
        patch :right
      end
    end
  end

  resources :instances, only: %i[ edit update ]

  resources :notes

  get "/apple-touch-icon/:size.:format", to: "home#apple_touch_icon"
  get "/favicon/:size.:format", to: "home#apple_touch_icon"
end

app/models/consumable.rb
class Consumable < ApplicationRecord
  include HasSlug

  has_many_attached :images
  after_save :update_unit_on_conversion, if: :base_quantity_unit_previously_changed?

  belongs_to :group
  has_many :consumable_categories,   dependent: :delete_all, autosave: true
  has_many :consumable_transactions, dependent: :delete_all, autosave: true
  has_many :notes,                   dependent: :delete_all, autosave: true, as: :parent
  has_many :domain_events,           dependent: :delete_all, autosave: true, as: :model
  has_many :categories,              dependent: :delete_all, autosave: true,              through: :consumable_categories

  scope :by_name,         ->{ order(Arel.sql("UNACCENT(#{quoted_table_name}.name), #{quoted_table_name}.id")) }
  scope :with_categories, ->{ includes(:categories) }
  scope :in_category,     ->(category){ includes(:categories).where(categories: { slug: category.slug }) }
  scope :search, ->(string){
    vector = "to_tsvector('fr', coalesce(consumables.name, '') || ' ' || coalesce(consumables.description, '') || ' ' || coalesce(consumables.building, ' ') || ' ' || coalesce(consumables.aisle, ' ') || ' ' || coalesce(consumables.shelf, ' ') || ' ' || coalesce(consumables.unit, ' '))"
    query = "plainto_tsquery('fr', :string)"
    where("#{vector} @@ #{query}", string: string).order(Arel.sql("ts_rank(#{vector}, #{query.sub(":string", Product.connection.quote(string))})"))
  }

  validates :name, presence: true, length: { minimum: 2 }
  validates :base_quantity_value, presence: true, numericality: { greater_than: 0, only_integer: false }
  validates :base_quantity_si_prefix, presence: true, inclusion: SI::ALL
  validates :base_quantity_unit, presence: true, inclusion: %w( unit pound litre gram ).freeze
  validates :internal_unit_price, :external_unit_price, presence: true, numericality: { greater_than_or_equal_to: 0, allow_blank: false }

  composed_of :base_quantity, class_name: "Quantity", mapping: [%w(base_quantity_value value), %w(base_quantity_si_prefix si_prefix), %w(base_quantity_unit unit)],
    constructor: ->(value, si_prefix, unit){ Quantity.new(value, si_prefix, unit) }

  # Only used to use the ActionView helpers
  # In reality, this attribute is absolutely unused
  attribute :image_url, :string

  def change_data(attributes, metadata: {})
    self.attributes = attributes
    domain_events << ConsumableNameChanged.new(data: {product_slug: slug, name: name, description: description}, metadata: metadata)                           if name_changed? || description_changed?
    domain_events << ConsumableLocationChanged.new(data: {product_slug: slug, building: building, aisle: aisle, shelf: shelf, unit: unit}, metadata: metadata) if location_changed?
    # domain_events << ConsumableCategoriesChanged.new(data: {product_slug: slug, categories: categories.map(&:name)}, metadata: metadata)
  end

  def add_note(attributes, metadata: {})
    notes.build(attributes).tap do |new_note|
      domain_events << NoteAddedToConsumable.new(
        data: {
          author_slug: new_note.author_slug,
          body: new_note.body,
          product_slug: slug,
        },
        metadata: metadata
      )
    end
  end

  def category_slugs
    categories.map(&:slug)
  end

  def category_slugs=(value)
    self.categories = Category.where(slug: Array(value).reject(&:blank?))
  end

  def has_location?
    building.present? || aisle.present? || shelf.present? || unit.present?
  end

  def location_changed?
    building_changed? || aisle_changed? || shelf_changed? || unit_changed?
  end

  def unit_price(internal: false)
    internal ? internal_unit_price : external_unit_price
  end

  def available_quantity
    consumable_transactions.
      reject(&:marked_for_destruction?).
      reject(&:new_record?).
      map(&:quantity).
      inject(zero_quantity, &:+)
  end

  def change_quantity(quantity, unit_price:, reason: nil, event: nil)
    if reason
      consumable_transactions.build(
        unit_price: unit_price || BigDecimal(0),
        quantity: quantity,
        reason: reason,
      )
    else
      ct   = consumable_transactions.detect{|ct| ct.event == event}
      ct ||= consumable_transactions.build(event: event)
      ct.quantity = quantity.scale(-1)
    end
  end

  def quantity_on(event)
    base = consumable_transactions
      .select{|ct| ct.event == event}
      .map(&:quantity)
      .inject(zero_quantity, &:+)
      .scale(-1)

    base.to(base_quantity.si_prefix).value / base_quantity.value
  end

  def unit_price_on(event)
    cts = event.consumable_transactions.select{|ct| ct.consumable == self}
    cts.map(&:unit_price).max || unit_price(internal: event.internal?)
  end

  def si_prefix
    base_quantity.si_prefix
  end

  # Returns a string to be used for ordering a list of products consistently
  #
  # @return [String] The key to use to order this item consistently
  def sort_key_for_display
    [name.downcase, id].map(&:to_s).join(":")
  end

  def sort_key_for_pickup
    [building, aisle, shelf, unit, name, id].map(&:to_s).join(":")
  end

  def zero_quantity
    Quantity.zero(base_quantity.unit)
  end

  private

  def update_unit_on_conversion
    consumable_transactions.reject(&:new_record?).reject(&:marked_for_destruction?).each do |ct|
      ct.update(quantity_unit: base_quantity_unit)
    end
  end
end

app/controllers/consumables/images_controller.rb
class Consumables::ImagesController < ApplicationController
  before_action :set_consumable
  before_action :set_image

  def left
    rotate(-90)
    respond_to do |format|
      format.html { redirect_to @consumable }
      format.js   { render action: :redraw_image }
    end
  end

  def right
    rotate(90)
    respond_to do |format|
      format.html { redirect_to @consumable }
      format.js   { render action: :redraw_image }
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to @consumable, notice: I18n.t("consumables.images.destroy.notice") }
      format.js
    end
  end

  private

  def set_consumable
    @consumable = current_group.consumables.find_by!(slug: params[:consumable_id])
  end

  def set_image
    @image = @consumable.images.find(params[:id])
  end

  def rotate(angle)
    basename = Rails.root + "tmp/#{SecureRandom.uuid}.jpg"
    updname  = basename.sub(".jpg", "-updated.jpg")

    begin
      tf = File.new(basename, "w:ASCII-8BIT")
      tf.write(@image.download)
      tf.close

      img = MiniMagick::Image.new(tf.path)
      img.rotate(angle)
      img.write(updname)

      File.open(updname, "r:ASCII-8BIT") do |io|
        @new_image = @consumable.images.attach(io: io, filename: @image.filename).first
      end
      @image.destroy

      # Process this ASAP, because there's a human waiting for it now
      ShrinkImageJob.set(priority: 0).enqueue(@consumable.id, @new_image.id)
    ensure
      File.unlink(basename) if File.exist?(basename)
      File.unlink(updname) if File.exist?(updname)
    end
  end
end

app/controllers/consumables/notes_controller.rb
class Consumables::NotesController < ApplicationController
  def create
    current_group.transaction do
      @consumable = current_group.consumables.find_by!(slug: params[:consumable_id])
      @consumable.add_note(note_params.merge(author: current_member), metadata: domain_event_metadata)
      @consumable.save!
    end

    redirect_to consumable_path(@consumable)
  end

  private

  def note_params
    params.require(:note).permit(:body)
  end
end

app/controllers/consumables_controller.rb
class ConsumablesController < ApplicationController
  before_action :set_consumable, only: [:show, :edit, :update, :destroy]
  before_action :load_categories, except: %i[ destroy ]

  def index
    @page_title = t(".page_title")

    @filter = params[:filter]

    @selected_category = @categories.detect{|category| category.slug == params[:category]}

    @consumables = current_group.consumables.with_attached_images.with_categories
    @consumables = @consumables.search(@filter) if @filter.present?
    @consumables = @consumables.in_category(@selected_category) if @selected_category
    @consumables = @consumables.by_name
    @consumables = @consumables.page(params[:page])
  end

  def show
    @page_title = @consumable.name
    @note = @consumable.notes.build
    @consumable_transaction = @consumable.consumable_transactions.build(quantity: Quantity.zero(@consumable.unit))
  end

  def new
    @page_title = t(".page_title")
    @consumable =
      if params[:clone_from].present?
        @clone_from = current_group.consumables.find_by!(slug: params[:clone_from])
        current_group.consumables.build(
          aisle: @clone_from.aisle,
          building: @clone_from.building,
          categories: @clone_from.categories,
          description: @clone_from.description,
          images: @clone_from.images,
          name: @clone_from.name,
          shelf: @clone_from.shelf,
          unit: @clone_from.unit,
        )
      else
        current_group.consumables.build
      end
  end

  def edit
    @page_title = t(".page_title", consumable_name: @consumable.name)
  end

  def create
    successful = current_group.transaction do
      @consumable = current_group.register_new_consumable(consumable_params, metadata: domain_event_metadata)

      @attached = []
      @attached.concat(@consumable.images.attach(params[:consumable][:images])) if params[:consumable][:images].present?
      @attached.concat(import(params[:consumable][:image_url]))

      if params[:clone_from].present?
        @clone_from = current_group.consumables.find_by!(slug: params[:clone_from])
        @clone_from.images.each do |attachment|
          @consumable.images.build(blob: attachment.blob)
        end
      end

      current_group.save.tap do
        @attached.each do |image|
          ShrinkImageJob.enqueue(@consumable.id, image.id)
        end if @attached
      end
    end

    if successful
      redirect_to @consumable, notice: t(".consumable_successfully_created")
    else
      @page_title = "New Consumable"
      render :new
    end
  end

  def update
    successful = current_group.transaction do
      @consumable.change_data(consumable_params, metadata: domain_event_metadata)

      @attached = []
      @attached.concat(@consumable.images.attach(params[:consumable][:images])) if params[:consumable][:images].present?
      @attached.concat(import(params[:consumable][:image_url]))

      @consumable.save.tap do
        @attached.each do |image|
          ShrinkImageJob.perform_later(@consumable.id, image.id)
        end if @attached
      end
    end

    if successful
      redirect_to @consumable, notice: t(".consumable_successfully_updated")
    else
      @page_title = "Edit #{@consumable.name}"
      render :edit
    end
  end

  def destroy
    @consumable.destroy
    redirect_to consumables_url, notice: t(".consumable_successfully_destroyed")
  end

  private

  def set_consumable
    @consumable = current_group.consumables.find_by!(slug: params[:id])
  end

  def consumable_params
    params.require(:consumable).permit(
      :name,
      :description,
      :building,
      :aisle,
      :shelf,
      :unit,
      :internal_unit_price,
      :external_unit_price,
      category_slugs: [],
    ).tap do |allowed|
      parsed_quantity = QuantityParser.new.parse(params.require(:consumable).require(:base_quantity))
      allowed[:base_quantity] = parsed_quantity
    end
  end

  def load_categories
    @categories = Category.by_name.to_a
  end

  def import(image_url)
    return [] if image_url.blank?

    uri = URI.parse(image_url)

    response = Net::HTTP.get_response(uri)

    @consumable.images.attach(
      io: StringIO.new(response.body),
      filename: File.basename(uri.path),
      content_type: response["Content-Type"],
    )
  end
end

app/views/consumables/_form.html.erb
<%= form_with(model: consumable, local: true) do |form| %>
  <%= hidden_field_tag :clone_from, @clone_from&.to_param %>
  <div class="grid-container">
    <div class="grid-x grid-padding-x">
      <% if consumable.errors.any? %>
        <div class="small-12 cell">
          <div id="error_explanation">
            <h2><%= pluralize(consumable.errors.count, "error") %> prohibited this consumable from being saved:</h2>

            <ul>
              <% consumable.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>

      <div class="small-12 cell">
        <%= form.label :name %>
        <%= form.text_field :name, autocomplete: false %>
      </div>

      <div class="small-12 medium-6 cell">
        <%= form.label :images %>
        <%= form.file_field :images, :multiple => true, :"aria-describedby" => "help-on-images", :autocomplete => false %>
        <p id="help-on-images" class="help-text"><%= t(".help_on_images") %></p>
      </div>

      <div class="small-12 medium-6 cell">
        <%= form.label :image_url %>
        <%= form.text_field :image_url, :"aria-describedby" => "help-on-images" %>
      </div>

      <div class="small-12 cell">
        <fieldset class="fieldset">
          <legend><%= t(".location_label") %></legend>
          <%= form.label :building %>
          <%= form.text_field :building %>

          <%= form.label :aisle %>
          <%= form.text_field :aisle %>

          <%= form.label :shelf %>
          <%= form.text_field :shelf %>

          <%= form.label :unit %>
          <%= form.text_field :unit %>
        </fieldset>
      </div>

      <div class="small-12 cell">
        <%= form.label :description %>
        <%= form.text_area :description, size: "10x5" %>
      </div>

      <div class="small-12 cell">
        <div class="grid-x grid-margin-x">
          <div class="small-12 medium-3 cell">
            <div class="grid-x grid-margin-x">
              <div class="small-auto cell">
                <%= form.label :internal_unit_price %>
                <%= form.number_field :internal_unit_price, min: 0, step: BigDecimal("0.01") %>
              </div>

              <div class="small-auto cell">
                <%= form.label :external_unit_price %>
                <%= form.number_field :external_unit_price, min: 0, step: BigDecimal("0.01") %>
              </div>
            </div>
          </div>

          <div class="small-12 medium-2 cell">
            <%= form.label :base_quantity %>
            <%= form.text_field :base_quantity, value: format_quantity(@consumable.base_quantity) %>
          </div>

        </div>
      </div>

      <div class="small-12 cell">
        <fieldset class="fieldset">
          <legend><%= t(".categories_label") %></legend>
          <div class="grid-container">
            <div class="grid-x grid-margin-x small-up-3 medium-up-4">
              <%= form.collection_check_boxes :category_slugs, @categories, :slug, ->(category){ t(category.name, scope: "categories") } do |b| %>
                <div class="cell">
                  <%= b.check_box %> <%= b.label %>
                </div>
              <% end %>
            </div>
          </div>
        </fieldset>
      </div>

      <div class="small-12 cell">
        <%= form.submit class: "button primary" %>
        <%= render partial: "shared/or" %>
        <% if @consumable.new_record? %>
          <%= link_to t(".cancel_button_label"), consumables_path, class: "button secondary" %>
        <% else %>
          <%= link_to t(".cancel_button_label"), @consumable, class: "button secondary" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/consumables/edit.html.erb
<%= render "form", consumable: @consumable %>

app/views/consumables/index.html.erb
<div class="grid-x grid-padding-x">
  <div class="large-9 medium-12 cell">
    <%= form_tag consumables_path, method: :get, class: "search-form" do %>
      <div class="grid-container">
        <div class="grid-x grid-padding-x">
          <div class="medium-shrink cell show-for-sr">
            <%= label_tag :filter, t(".filter_label"), class: "middle" %>
          </div>
          <div class="medium-shrink cell">
            <%= text_field_tag :filter, @filter, placeholder: t(".filter_label"), autocomplete: false %>
          </div>

          <div class="medium-shrink cell show-for-sr">
            <%= label_tag :category, t(".category_label"), class: "middle" %>
          </div>
          <div class="medium-shrink cell">
            <%= select_tag :category, options_from_collection_for_select(@categories, :slug, ->(category){ t(category.name, scope: "categories") }, @selected_category ? @selected_category.slug : nil), include_blank: true %>
          </div>

          <div class="medium-auto cell">
            <%= submit_tag t(".search_button_label"), name: nil, class: "button" %> <%= link_to t(".view_all_button_label"), consumables_path, class: "button secondary" %>
          </div>
        </div>
      </div>
    <% end %>

    <% if current_member.inventory_director? %>
      <div class="grid-container">
        <div class="grid-x grid-margin-x">
          <div class="cell">
            <%= link_to t(".new_consumable_button_label"), new_consumable_path, class: "button hide-for-large" %>
          </div>
        </div>
      </div>
    <% end %>

    <div class="grid-container">
      <div class="grid-x grid-margin-x">
        <div class="cell">
          <table class="hover stack consumable-list">
            <thead>
              <tr>
                <th><%= t(".name_header") %></th>
                <th><%= t(".quantity_header") %></th>
                <th><%= t(".location_header") %></th>
                <th><%= t(".description_header") %></th>
                <th><%= t(".categories_header") %></th>
              </tr>
            </thead>

            <tbody>
              <% if @consumables.empty? %>
                <tr>
                  <td colspan="5"><%= t(".sorry_no_elements") %></td>
                </tr>
              <% end %>
              <% @consumables.each do |consumable| %>
                <tr>
                  <td>
                    <%= link_to consumable.name, consumable %> <br>
                    <%= entity_image consumable, height: 250 %>
                  </td>
                  <td><%= number_with_delimiter 0 %></td>
                  <td><%= format_product_location(consumable) %></td>
                  <td><%= consumable.description %></td>
                  <td><%= consumable.categories.map(&:name).map{|name| t(name, scope: "categories") }.sort_by(&:downcase).to_sentence %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @consumables %>
        </div>
      </div>
    </div>
  </div>

  <% if current_member.inventory_director %>
    <div class="large-3 medium-12 cell show-for-large">
      <%= link_to t(".new_consumable_button_label"), new_consumable_path, class: "button expanded" %>
    </div>
  <% end %>
</div>

app/views/consumables/new.html.erb
<%= render "form", consumable: @consumable %>

app/views/consumables/show.html.erb
<div class="grid-x grid-margin-x">
  <div class="large-9 medium-12 cell">
    <%= form_tag event_reservations_path(@event, @consumable) do %> <%= submit_tag t(".add_to_cart_label"), name: :add, class: "button small hide-for-large" %>
    <% end if @event %>
    <%= link_to t(".edit_button_label"), edit_consumable_path(@consumable), class: "button small hide-for-large" if current_member.inventory_director? %>
    <%= link_to t(".clone_button_label"), new_consumable_path(clone_from: @consumable), class: "button small hide-for-large" if current_member.inventory_director? %>
    <%= link_to t(".back_to_list_button_label"), consumables_path, class: "button secondary small hide-for-large" %>
    <%= link_to t(".delete_button_label"), consumable_path(@consumable), method: :delete, class: "button small alert hide-for-large" if current_member.inventory_director? %>

    <div class="grid-x grid-padding-x small-up-1 medium-up-3">
      <% @consumable.images.select(&:blob).sort_by{|blob| blob.filename.to_s.downcase}.each do |image| %>
        <%= render partial: "shared/image", locals: { entity: @consumable, image: image } %>
      <% end %>
    </div>

    <div>
      <strong><%= t("name", scope: "activerecord.attributes.consumable") %>:</strong>
      <%= @consumable.name %>
    </div>

    <div>
      <strong><%= t("location", scope: "activerecord.attributes.consumable") %>:</strong>
      <%= format_product_location(@consumable) %>
    </div>

    <div>
      <strong><%= t("base_quantity", scope: "activerecord.attributes.consumable") %>:</strong>
    </div>

    <div>
      <strong><%= t("internal_unit_price", scope: "activerecord.attributes.consumable") %>:</strong>
      <%= number_to_currency @consumable.internal_unit_price %> / <%= format_quantity @consumable.base_quantity %>
    </div>

    <div>
      <strong><%= t("external_unit_price", scope: "activerecord.attributes.consumable") %>:</strong>
      <%= number_to_currency @consumable.external_unit_price %> / <%= format_quantity @consumable.base_quantity %>
    </div>

    <div>
      <strong><%= t("description", scope: "activerecord.attributes.consumable") %>:</strong>
      <%= simple_format @consumable.description %>
    </div>

    <%= form_for @consumable_transaction, url: consumable_transactions_path(@consumable) do |f| %>
      <h3><%= t ".consumable_reservation_history_header" %></h3>
      <table>
        <col width="15%"/>
        <col width="15%"/>
        <col width="50%"/>
        <col width="20%"/>
        <thead>
          <tr>
            <th><%= t(".date_header") %></th>
            <th><%= t(".quantity_header") %></th>
            <th colspan="2"><%= t(".reason_or_event_header") %></th>
          </tr>
        </thead>
        <tbody>
          <% @consumable.consumable_transactions.sort_by(&:date).reject(&:new_record?).each do |consumable_transaction| %>
            <tr>
              <td><%= l consumable_transaction.date, format: :with_year %></td>
              <td class="quantity"><%= format_quantity consumable_transaction.quantity %></td>
              <td colspan="2">
                <% if consumable_transaction.event %>
                  <%= link_to consumable_transaction.event.title, consumable_transaction.event %>
                <% else %>
                  <%= consumable_transaction.reason %>
                <% end %>
              </td>
            </tr>
          <% end %>
          <% if current_member.inventory_director? %>
            <tr>
              <td><%= l Date.current, format: :with_year %></td>
              <td>
                <%= f.text_field :quantity, value: format_quantity(@consumable_transaction.quantity, si_prefix: SI::BASE), class: "quantity", required: true %>
              </td>
              <td>
                <%= f.text_field :reason, required: true %>
              </td>
              <td>
                <%= f.submit class: "button primary small" %>
              </td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td><%= l Date.current, format: :with_year %></td>
            <td class="quantity">
              <%= format_quantity @consumable.available_quantity %>
            </td>
            <td colspan="2"></td>
          </tr>
        </tfoot>
      </table>
    <% end %>
  </div>

  <div class="large-3 medium-12 cell show-for-large">
    <%= form_tag event_reservations_path(@event, @consumable) do %>
      <h4><%= @event.title %></h4>
      <h6><%= format_date_range(@event.real_date_range) %></h6>
      <%= hidden_field_tag "consumables[#{@consumable.slug}]", "1" %>
      <%= submit_tag t(".add_to_cart_label"), name: :add, class: "button expanded" %>
      <hr>
    <% end if @event %>
    <%= link_to t(".edit_button_label"), edit_consumable_path(@consumable), class: "button expanded" if current_member.inventory_director? %>
    <%= link_to t(".clone_button_label"), new_consumable_path(clone_from: @consumable), class: "button expanded" if current_member.inventory_director? %>
    <%= link_to t(".back_to_list_button_label"), consumables_path, class: "button secondary expanded" %>

    <hr>

    <% if current_member.inventory_director? %>
      <%= link_to t(".delete_button_label"), consumable_path(@consumable), method: :delete, class: "button alert expanded" %>
      <hr>
    <% end %>

    <%= render partial: "shared/notes", locals: { parent: @consumable, note: @note, create_note_path: consumable_notes_path(@consumable) } %>
  </div>

  <div class="small-12 cell hide-for-large">
    <hr>
    <%= render partial: "shared/notes", locals: { parent: @consumable, note: @note, create_note_path: consumable_notes_path(@consumable) } %>
  </div>

  <div class="small-12 cell hide-for-large">
    <%= link_to t(".back_to_list_button_label"), consumables_path, class: "button secondary small hide-for-large" %>
  </div>
</div>